In [14]:
from quantum_logical.operators import selective_destroy
from quantum_logical.interaction import ConversionGainInteraction
from weylchamber import c1c2c3
import numpy as np
import qutip
from qutip.operators import destroy

In [15]:
op = (
    selective_destroy(levels=3, from_level=1, to_level=0)
    + selective_destroy(3, 1, 0).dag()
    + selective_destroy(3, 2, 1)
    + selective_destroy(3, 2, 1).dag()
)
w = qutip.identity(3) + (1 / np.sqrt(2) * op)
w

Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = True
Qobj data =
[[1.         0.70710678 0.        ]
 [0.70710678 1.         0.70710678]
 [0.         0.70710678 1.        ]]

In [16]:
H = qutip.tensor(w, w)
t = np.pi
u = (-1j * H * t).expm()
u

Quantum object: dims = [[3, 3], [3, 3]], shape = (9, 9), type = oper, isherm = True
Qobj data =
[[ 0.5  0.   0.5  0.   0.   0.   0.5  0.  -0.5]
 [ 0.   1.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.5  0.   0.5  0.   0.   0.  -0.5  0.   0.5]
 [ 0.   0.   0.   1.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   1.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   1.   0.   0.   0. ]
 [ 0.5  0.  -0.5  0.   0.   0.   0.5  0.   0.5]
 [ 0.   0.   0.   0.   0.   0.   0.   1.   0. ]
 [-0.5  0.   0.5  0.   0.   0.   0.5  0.   0.5]]

In [17]:
# verify makes an CZ_gf gate
# convert to 2Q between g and f by removing indexes connected to e
# (quick and dirty way to trace out e)
indices = [0, 2, 6, 8]
reduced_matrix = u[np.ix_(indices, indices)]
print(c1c2c3(reduced_matrix))
u

(0.5, 0.0, 0.0)


Quantum object: dims = [[3, 3], [3, 3]], shape = (9, 9), type = oper, isherm = True
Qobj data =
[[ 0.5  0.   0.5  0.   0.   0.   0.5  0.  -0.5]
 [ 0.   1.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.5  0.   0.5  0.   0.   0.  -0.5  0.   0.5]
 [ 0.   0.   0.   1.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   1.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   1.   0.   0.   0. ]
 [ 0.5  0.  -0.5  0.   0.   0.   0.5  0.   0.5]
 [ 0.   0.   0.   0.   0.   0.   0.   1.   0. ]
 [-0.5  0.   0.5  0.   0.   0.   0.5  0.   0.5]]

In [18]:
reduced_matrix

array([[ 0.5+0.j,  0.5+0.j,  0.5+0.j, -0.5+0.j],
       [ 0.5+0.j,  0.5+0.j, -0.5+0.j,  0.5+0.j],
       [ 0.5+0.j, -0.5+0.j,  0.5+0.j,  0.5+0.j],
       [-0.5+0.j,  0.5+0.j,  0.5+0.j,  0.5+0.j]])