In [67]:
from quantum_logical.operators import selective_destroy
from quantum_logical.interaction import ConversionGainInteraction
from weylchamber import c1c2c3
import numpy as np

In [68]:
# conventional ladder operator
a = destroy(3, 2)
print(a)

print("\n")
# selective ladder operator
a = selective_destroy(3, 2, 1)
print(a)

Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = False
Qobj data =
[[0.         1.73205081 0.        ]
 [0.         0.         2.        ]
 [0.         0.         0.        ]]


Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = False
Qobj data =
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [69]:
H = ConversionGainInteraction(3 * np.pi / 8, np.pi / 8)
print(u := H.construct_U(1.0))
print(c1c2c3(u.full()))

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.92387953+0.j         0.        +0.j         0.        +0.j
  0.        -0.38268343j]
 [0.        +0.j         0.38268343+0.j         0.        -0.92387953j
  0.        +0.j        ]
 [0.        +0.j         0.        -0.92387953j 0.38268343+0.j
  0.        +0.j        ]
 [0.        -0.38268343j 0.        +0.j         0.        +0.j
  0.92387953+0.j        ]]
(0.5, 0.25, 0.0)


In [77]:
from quantum_logical.interaction import ConversionGainFiveWave

H = ConversionGainFiveWave(np.pi / 2, 0)
print(u := H.construct_U(1.0))

Quantum object: dims = [[3, 3], [3, 3]], shape = (9, 9), type = oper, isherm = False
Qobj data =
[[1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.-1.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.-1.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j]]
