In [87]:
from quantum_logical.operators import selective_destroy
from quantum_logical.interaction import ConversionGainInteraction
from weylchamber import c1c2c3
import numpy as np
import qutip
from quantum_logical.operators import reduce_to_two_qubit_subspace

In [88]:
# conventional ladder operator
a = qutip.destroy(3, 2)
print(a)

print("\n")
# selective ladder operator
a = selective_destroy(3, 2, 1)
print(a)

Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = False
Qobj data =
[[0.         1.73205081 0.        ]
 [0.         0.         2.        ]
 [0.         0.         0.        ]]


Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = False
Qobj data =
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [92]:
H = ConversionGainInteraction(np.pi / 4, np.pi / 4, transmon_levels=3)
u = H.construct_U(1.0)

# verify makes a CNOT_ge gate
# convert to 2Q between g and e by removing indices connected to f
reduced_u = reduce_to_two_qubit_subspace(u, [0, 1])
print(c1c2c3(reduced_u))
u

(0.5, 0.0, 0.0)


Quantum object: dims = [[3, 3], [3, 3]], shape = (9, 9), type = oper, isherm = False
Qobj data =
[[0.70710678+0.j         0.        +0.j         0.        +0.j
  0.        +0.j         0.        -0.70710678j 0.        +0.j
  0.        +0.j         0.        +0.j         0.        +0.j        ]
 [0.        +0.j         0.70710678+0.j         0.        +0.j
  0.        -0.70710678j 0.        +0.j         0.        +0.j
  0.        +0.j         0.        +0.j         0.        +0.j        ]
 [0.        +0.j         0.        +0.j         1.        +0.j
  0.        +0.j         0.        +0.j         0.        +0.j
  0.        +0.j         0.        +0.j         0.        +0.j        ]
 [0.        +0.j         0.        -0.70710678j 0.        +0.j
  0.70710678+0.j         0.        +0.j         0.        +0.j
  0.        +0.j         0.        +0.j         0.        +0.j        ]
 [0.        -0.70710678j 0.        +0.j         0.        +0.j
  0.        +0.j         0.70710678+0.j         

In [93]:
from quantum_logical.interaction import ConversionGainFiveWave

H = ConversionGainFiveWave(np.pi / 2, 0)
u = H.construct_U(1.0)

# verify makes an iSWAP_gf gate
# convert to 2Q between g and f by removing indexes connected to e
reduced_u = reduce_to_two_qubit_subspace(u, [0, 2])
print(c1c2c3(reduced_u))
u

(0.5, 0.5, 0.0)


Quantum object: dims = [[3, 3], [3, 3]], shape = (9, 9), type = oper, isherm = False
Qobj data =
[[1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.-1.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.-1.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j]]

In [97]:
from quantum_logical.interaction import CNOT_FC_EF

H = CNOT_FC_EF(np.pi / 4, np.pi / 4)
u = H.construct_U(1.0)

# verify makes an CNOT_ef gate
# convert to 2Q between e and f by removing indexes connected to g
reduced_u = reduce_to_two_qubit_subspace(u, [1, 2])
print(c1c2c3(reduced_u))
u

(0.5, 0.0, 0.0)


Quantum object: dims = [[3, 3], [3, 3]], shape = (9, 9), type = oper, isherm = False
Qobj data =
[[1.        +0.j         0.        +0.j         0.        +0.j
  0.        +0.j         0.        +0.j         0.        +0.j
  0.        +0.j         0.        +0.j         0.        +0.j        ]
 [0.        +0.j         1.        +0.j         0.        +0.j
  0.        +0.j         0.        +0.j         0.        +0.j
  0.        +0.j         0.        +0.j         0.        +0.j        ]
 [0.        +0.j         0.        +0.j         1.        +0.j
  0.        +0.j         0.        +0.j         0.        +0.j
  0.        +0.j         0.        +0.j         0.        +0.j        ]
 [0.        +0.j         0.        +0.j         0.        +0.j
  1.        +0.j         0.        +0.j         0.        +0.j
  0.        +0.j         0.        +0.j         0.        +0.j        ]
 [0.        +0.j         0.        +0.j         0.        +0.j
  0.        +0.j         0.70710678+0.j         