In [1]:
# explicit tutorial on the encoding
# what gates do encoding and detection
# the known solutions are the 5-wave and parallel 3-wave
# (we don't know if there exists others yet)
# but we need to first be able to simulate the faults and effective increases in lifetimes
# if that the qubits had lifetimes and errro channels
import numpy as np
from IPython.display import display, Math

In [2]:
from quantum_logical.conversiongain import QubitInteraction

# TODO refactor to conversion gain
# we should be able to return the equation from the class
H = QubitInteraction(gc=np.pi / 2, gg=0, transmon_levels=2)
display(Math(str(H)))
U = H.construct_U(t=1.0)
print(U)

ImportError: cannot import name 'QubitInteraction' from 'quantum_logical.conversiongain' (/home/evm9/quantum_logical/src/quantum_logical/conversiongain.py)

Quick introduction using standard phase repetition code
\begin{align}
|L_0\rangle = |+++\rangle\\
|L_1\rangle = |---\rangle
\end{align}

such that $|\psi\rangle = \alpha |L_0\rangle + \beta |L_1\rangle$


In [ ]:
from quantum_logical.basis import PhaseReptition

encoding = PhaseReptition()

In [ ]:
# to initialize the encoding:
# encoding.initialize()

AttributeError: 'PhaseReptition' object has no attribute 'initialize'

To create logical operators use the following transformation:
\begin{align*}
A = |L_0\rangle\langle0| + |L_1\rangle\langle1|\\
U' = A U A^\dagger
\end{align*}
,where U is unitary that acts on the $|0\rangle$ and $|1\rangle$ states.


In [ ]:
from qiskit import QuantumCircuit
from qiskit.quantum_info.operators import Operator

qc = QuantumCircuit(3)
qc.cx(0, 1)
qc.cx(0, 2)
Operator(qc).data.shape

(8, 8)

In [ ]:
encoding.logical_basis.transform_operator

Quantum object: dims = [[2, 2, 2], [2]], shape = (8, 2), type = oper, isherm = False
Qobj data =
[[ 0.35355339  0.35355339]
 [ 0.35355339 -0.35355339]
 [ 0.35355339 -0.35355339]
 [ 0.35355339  0.35355339]
 [ 0.35355339 -0.35355339]
 [ 0.35355339  0.35355339]
 [ 0.35355339  0.35355339]
 [ 0.35355339 -0.35355339]]

Next,


In [ ]:
from quantum_logical.basis import SNAILConcatWithAncilla

encoding = SNAILConcatWithAncilla()
encoding.logical_basis.transform_operator

Quantum object: dims = [[3, 3, 3], [2]], shape = (27, 2), type = oper, isherm = False
Qobj data =
[[ 0.35355339  0.35355339]
 [ 0.          0.        ]
 [ 0.35355339 -0.35355339]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.35355339 -0.35355339]
 [ 0.          0.        ]
 [ 0.35355339  0.35355339]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.35355339 -0.35355339]
 [ 0.          0.        ]
 [ 0.35355339  0.35355339]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.35355339  0.35355339]
 [ 0.          0.        ]
 [ 0.35355339 -0.35355339]]

In [18]:
from quantum_logical.conversiongain import (
    ConversionGainThreeWave,
    ConversionGainFiveWave,
)

H = ConversionGainThreeWave(gc=np.pi / 2, gg=0, transmon_levels=2)
display(Math(str(H)))
U = H.unitary(t=1.0)
print(U)

<IPython.core.display.Math object>

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.-1.j 0.+0.j]
 [0.+0.j 0.-1.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j]]


In [ ]:
# multiply this unitary to the following state
# |e> o\otimes [\alpha |g+f> + \beta |g-e>]
state = 

In [ ]:
H = ConversionGainFiveWave(gc=np.pi / 2, gg=0)
display(Math(str(H)))
U = H.unitary(t=1.0)
print(U)

<IPython.core.display.Math object>

Quantum object: dims = [[3, 3], [3, 3]], shape = (9, 9), type = oper, isherm = True
Qobj data =
[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.]]


In [ ]:
# todo, check decode solution with 3-, 5-wave gates
# show that 5-wave stays in encoding, 3-wave does not
# is_centralizer()

In [ ]:
from qutip import *

In [ ]:
qutip.create(3)

Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = False
Qobj data =
[[0.         0.         0.        ]
 [1.         0.         0.        ]
 [0.         1.41421356 0.        ]]

In [6]:
from quantum_logical.qubitoperator import QubitOperator, Transition

# Example
op_a_ge = QubitOperator("a", Transition.GE, transmon_levels=3)
print(op_a_ge.to_qutip())

# op_a_ge_dag = op_a_ge.dag()
# print(op_a_ge_dag.to_qutip())

Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = False
Qobj data =
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 0. 0.]]
