In [10]:
# run this same experiment again but instead of 2,0,0 -> 0,0,2 have 2,0,0 -> 0,1,1 this would be cool 
# declaring all dependancies    
import qutip as qt
import numpy as np
from quantum_logical.pulsesim import QuantumSystem, Pulse
from quantum_logical.pulsesim.mode import QubitMode, SNAILMode, CavityMode
from quantum_logical.pulsesim.build_hamiltonian import Build_hamiltonian
import matplotlib.pyplot as plt
from quantum_logical.channel import AmplitudeDamping, PhaseDamping
from quantum_logical.trotter import TrotterGroup
from quantum_logical.interaction import ConversionGainInteraction
from qutip import Options
from tqdm import tqdm_notebook as tqdm
from progressbar import progressbar
from threading import Thread
from multiprocessing.pool import Pool, ThreadPool
from numpy.linalg import eig
from quantum_logical.creating_operators import Creating_operators

# opts = Options(nsteps=1e6, atol=1e-8, rtol=1e-6)
# p_bar = qt.ui.TextProgressBar()  # None
opts = {"nsteps": 1e6, "atol": 1e-8, "rtol": 1e-6, "progress_bar": "text"}

In [11]:
fund_ops_list = []
H = Creating_operators(qubit_count=2, qubit_dim=3)
fund_ops_list.append(H.create_ops_unconventional_annhilation(from_level=0, to_level=1))  # this is not necessary with the new addition for the operator 
fund_ops_list.append(H.create_ops_unconventional_annhilation(from_level=1, to_level=2))

# # list of operators based on the fundamental single qubit operators 
# ops_list = []
# ops_list.append(qt.tensor(fund_ops_list[0], fund_ops_list[1].dag()))
# ops_list.append(qt.tensor(fund_ops_list[1], fund_ops_list[0].dag()))
# ops_list.append(qt.tensor(fund_ops_list[1].dag(), fund_ops_list[0]))
# ops_list.append(qt.tensor(fund_ops_list[0].dag(), fund_ops_list[1]))

# list of operators based on the full dimension operators
ops_list = []
ops_list.append(H.creating_ops_full_dim(qubit1_from=1, qubit1_to=0, qubit2_from=1, qubit2_to=2))
ops_list.append(H.creating_ops_full_dim(qubit1_from=2, qubit1_to=1, qubit2_from=0, qubit2_to=1))
ops_list.append(H.creating_ops_full_dim(qubit1_from=1, qubit1_to=2, qubit2_from=1, qubit2_to=0))
ops_list.append(H.creating_ops_full_dim(qubit1_from=0, qubit1_to=1, qubit2_from=2, qubit2_to=1))

# this doesnt work yet but it is necessary for this to work
# ops_list2 = []
# ops_list1 = np.zeros((9,9), dtype=complex)
# for i in range(len(ops_list)):
#     for j in range(ops_list[i].shape[0]):
#         for k in range(ops_list[i].shape[0]):
#             ops_list1[j,k] = ops_list[i][j,k]
#     ops_list2.append(ops_list1)

# for i in range(len(ops_list2)):
#     ops_list2[i] = qt.Qobj(ops_list2[i])

# ops_list[0].shape[0]


In [12]:
op1 = np.linspace(0,10,10)
op2 = np.linspace(0,10,10)
op3 = np.linspace(0,10,10)
op4 = np.linspace(0,10,10)
coeff_list = [(i, j, k, l) for i in op1 for j in op2 for k in op3 for l in op4]
fid = []

for i in range(len(coeff_list)):
    H_new = H.total_operator(coeff_list=coeff_list[i], ops_list=ops_list)
    prop_calc = H.propagator(H=H_new, T=100)
    ideal_cnot = H.ideal_cnot_gate(from_level=1, to_level=0, control_level=1)
    fid.append(qt.process_fidelity(prop_calc, ideal_cnot))

fid

[0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716049383,
 0.6049382716

In [13]:
# do something that tries the conversion gain terms as opposed to what is being done above
# try introducing an imaginary coefficient 
# will have to eventually make this time dependant in order to find the hamiltonian that you are looking for to create the cnot based on these terms 

In [14]:
# this is the beginning of the actual experiment once the cnot gate is found and optimized
# once this is done everything else should fly by and be easy
# try doing this via the hamiltonian method and see if you get something that is much more promising
# if you want you can keep the not gate as a regular matrix that acts instantly and build the cnot using the hamiltonian method and see which one truly messes with the system noise wise

In [15]:
# this gives the x gate which converts e to f and f to e 
# by doing a regular x gate without applying a specific time to the qubits you get to truly analyze the difference between the five wave and the three wave cnot gate 
H.not_gate(exchange_levels=[1,2])

Quantum object: dims=[[3], [3]], shape=(3, 3), type='oper', dtype=Dense, isherm=True
Qobj data =
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]

In [16]:
# building the optimizer over the operator
op1 = op2 = op3 = op4 = np.linspace(0,10,2)
phase1 = phase2 = phase3 = phase4 = np.linspace(0,np.pi/2,2)
coeff_list = [(i, j, k, l) for i in op1 for j in op2 for k in op3 for l in op4]
phase_list = [(i, j, k, l) for i in phase1 for j in phase2 for k in phase3 for l in phase4]

# def sim_task(coeffs, phases):
    # coeff_list = coeffs
    # phase_list = phases

    # coeffs_new = H.Create_coeff(coeff_list=coeff_list, phase_list=phase_list)
    # H_new = H.total_operator(coeff_list=coeffs_new, ops_list=ops_list)
    # U = H.propagator(H=H_new, T=100)
    # ideal_cnot = H.ideal_cnot_gate(from_level=0, to_level=1, control_level=1)
    # fid = qt.fidelity(U, ideal_cnot)

    # return fid, coeff_list, phase_list

# result = qt.parallel.parallel_map(task=sim_task, values=(coeff_list, phase_list), progress_bar=True)
fid = []
# for loop for speed
for i,j in zip(coeff_list, phase_list)
    coeffs_new = H.Create_coeff(coeff_list=i, phase_list=j)
    H_new = H.total_operator(coeff_list=coeffs_new, ops_list=ops_list)
    U = H.propagator(H=H_new, T=100)
    ideal_cnot = H.ideal_cnot_gate(from_level=0, to_level=1, control_level=1)
    fid.append(qt.fidelity(U, ideal_cnot))



SyntaxError: invalid syntax (3390622216.py, line 22)

In [19]:
hnew = ConversionGainInteraction(gg=np.pi / 4, gc= np.pi / 4, transmon_levels=3)
prop_cnot = hnew.construct_U(1.0)
prop_cnot

Quantum object: dims=[[3, 3], [3, 3]], shape=(9, 9), type='oper', dtype=Dense, isherm=False
Qobj data =
[[0.70710678+0.j         0.        +0.j         0.        +0.j
  0.        +0.j         0.        -0.70710678j 0.        +0.j
  0.        +0.j         0.        +0.j         0.        +0.j        ]
 [0.        +0.j         0.70710678+0.j         0.        +0.j
  0.        -0.70710678j 0.        +0.j         0.        +0.j
  0.        +0.j         0.        +0.j         0.        +0.j        ]
 [0.        +0.j         0.        +0.j         1.        +0.j
  0.        +0.j         0.        +0.j         0.        +0.j
  0.        +0.j         0.        +0.j         0.        +0.j        ]
 [0.        +0.j         0.        -0.70710678j 0.        +0.j
  0.70710678+0.j         0.        +0.j         0.        +0.j
  0.        +0.j         0.        +0.j         0.        +0.j        ]
 [0.        -0.70710678j 0.        +0.j         0.        +0.j
  0.        +0.j         0.70710678+0.j  

In [ ]:
# try this set with everything that evan and i talked about the cnot is already made but i need to learn about the invariant things that allow this type of cnot
#  to be like the cnot that is ideal